In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from sklearn import datasets

In [ ]:
df=datasets.load_breast_cancer(as_frame=True)

In [ ]:
data=df.data
target=df.target
data['target']=target
pd.set_option('display.max_columns',None)

In [ ]:
data.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,radius error,texture error,perimeter error,area error,smoothness error,compactness error,concavity error,concave points error,symmetry error,fractal dimension error,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [ ]:
df['target'].value_counts()

target
1    357
0    212
Name: count, dtype: int64

In [ ]:
X= data.drop('target',axis=1)   ##always be in dataFrame
y=data['target']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=417)

In [ ]:
X_train.shape,X_test.shape

((455, 30), (114, 30))

In [ ]:
data.shape

(569, 31)

In [ ]:
X_train.index

Index([ 32, 466, 147,  41, 330, 376, 214,  16,  23, 342,
       ...
       272,  68, 238, 561, 252,  78, 167, 242, 467, 331],
      dtype='int64', length=455)

classification deals with discrete outcomes (e.g., yes/no, categories)

regression handles continuous values (e.g., price, temperature)

#Linear SVC

In [ ]:
from sklearn.svm import LinearSVC

In [ ]:
model = LinearSVC(penalty="l2",loss='squared_hinge',C=10)

Fit is used to read the data

In [ ]:
model.fit(X_train,y_train)

LinearSVC(C=10)

In [ ]:
X_test.iloc[:3]

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,radius error,texture error,perimeter error,area error,smoothness error,compactness error,concavity error,concave points error,symmetry error,fractal dimension error,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
30,18.63,25.11,124.80,1088.0,0.10640,0.18870,0.23190,0.12440,0.2183,0.06197,0.8307,1.466,5.574,105.00,0.006248,0.03374,0.05196,0.011580,0.02007,0.004560,23.15,34.01,160.50,1670.0,0.14910,0.4257,0.6133,0.18480,0.3444,0.09782
407,12.85,21.37,82.63,514.5,0.07551,0.08316,0.06126,0.01867,0.1580,0.06114,0.4993,1.798,2.552,41.24,0.006011,0.04480,0.05175,0.013410,0.02669,0.007731,14.40,27.01,91.63,645.8,0.09402,0.1936,0.1838,0.05601,0.2488,0.08151
362,12.76,18.84,81.87,496.6,0.09676,0.07952,0.02688,0.01781,0.1759,0.06183,0.2213,1.285,1.535,17.26,0.005608,0.01646,0.01529,0.009997,0.01909,0.002133,13.75,25.99,87.82,579.7,0.12980,0.1839,0.1255,0.08312,0.2744,0.07238

In [ ]:
y_test.iloc[:3]

30     0
407    1
362    1
Name: target, dtype: int64

In [ ]:
model.predict(X_test.iloc[0:3])

array([0, 1, 1])

In [ ]:
y_test.iloc[18:24]

400    0
123    1
372    0
132    0
344    1
497    1
Name: target, dtype: int64

In [ ]:
model.predict(X_test.iloc[18:24])

array([0, 1, 0, 0, 1, 1])

In [ ]:
model.score(X_test,y_test)

0.9649122807017544

In [ ]:
import joblib
joblib.dump(model,'model.pkl')

['model.pkl']